language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
deploy:
  provider: heroku
  api_key:
    secure: 1jzYC9dfr+DAsl1CsZjrZEY9J1g3XyypQN+khAt8wxfvuU8R7HVj2vxLVz0B80dNkIQxAb+ucna5Z1T6f52SRsZDlkyrkssOOvcAvY2d+LQwzgLbZeFwsQAt7Ex+i/QPIYENlsy0lSP1D6VLy4jBmZQth/MRjsHD2kzbIPtvffS6LLGsxLH58GWfFaupbL6ROWHShxxyAS98zPzdz5dcHB1gnk4HjEo1G/tCFZKT7TkhAbceP5l0J5osKKEJoCqkdXUaU5cj58vJ/oKaTHlBHONSpi/cLh3uCbSmHatCteuhccoNMNyBfURX2g+WlJgz8EyKZqrjUexdxRJJXa6i99/DFtmCcZb1OC0KWi9A8ud/K2bdDSoVtKveCjBrIag62qMamI6sSA+8NKkhjPivbPlejj1Fh+PztRaMr5KxgjZPbT0pMY+x0uKk1vd+kSiObooBjOnOMk3Gdo6hW/Ax0NFZS61gJYj4YaMrx8/pJdBNoNie76NvVQ9BmN9utF6J59eRY/3wE7td8WMeD/882eFLguGGFCER/M2OXEeVLyPKFpswNVAfkxWVph5Pc/QAnLBxgQt189C0sLjO1o3tYlKhu+Se7n7zBav+jiS8FcpZSY7Gnx2a0uvgWyAjIbkZyACOGXVuBRnHF4SvRsTwsjAjp6JrFLoX5BA2oYer3ro=
  app: mysterious-dusk-26630
  on:
    repo: sgraton/AirKong
env:
  secure: vO6nshZTcbpObyljtLSH6T3kMCKwodmTGwD9C15YOxNvn1nBI830jG7YlpmNLyae/nI/aAPSn9cAHKHB6Jv+fFdMsBfgdLQ+1eH2EGxuG4nptyDvYbwDtPhYRFMFZNSpYG9TZZrsI8xf0J8E58tD3jgMJih5qhneCHDpcCCVyvVc6p4rDN/NA5ePVkGVlAottSfGqj2JXmZ5S/mf3TbaB18AxokeUfBmkTmmhyTIzV4ootg/uKTHeKDZiIpT5gd3aSDoZFHkIsj3bLo9m7+WZ7hmdCMkBuSnyTOoiRcuNQ+Q/YaqBxC4CDLyHHkH2rhWQr5EC/4YBeKro2lNni0KFUIE+EH/VMWrj+zyLeNxPO+x1lO3a+7cGRuWiuvNpuM56MoADaboWl6Vda7xfBV66MfMPUyjU7WB1s0iagB6teVs6e4Bf3vhboPx6PYwhK4bra9WVN5dfj/jlzT2aePsnME/LKPcimQKtKhgi0p63252R0sLeOyoUO4XcbURtLwVajxMy+cMShKXLT3CGe+vDBkiyDDllzpWY1T+O4EUL9AJUGBq3FTvretG6u8ik4usTdBvxKq8VFlBWLrEbhVMImbXd4H3V7zDIJ/8tQtkiI4X74J1Dg2Tt4kW+7ZujpK7ID+LHMwI2QKhT1ZdQX7X3gzshujL1wTuUU9H1RvGVw4=
  global:
    secure: Mrqle9z6UTbRVMslRuglPmkU7xfILcs7Hi+gYQrs7MOCyDGVcATrUQST+8TfNAH21iF86qOiGv9wnXnrw/0AJ9Ep0iubM6KVsKJgszGCqt9CT8JEcSW3qUqOE14/WJcqjnyXfwBCtBckAVxSx6d5yovXRwQ5Az8QYtoW4qlFOhSzNVgWqD9+ADvs7IydLYS4gnqBcvJEVLnJRzM7ePJa33JBMTBWKqCeS42sCN/1t4Scr9l7bl/eMyeM3AnDg9EtA0ilbI0zmmthNn4p2vqoDYQPsF28PxIDfGnS1sIxCGj87ywY721r6Li8CwY8Swka0+wYKXRi+P7RrWp7Qgnfllkt4NdziyqaNgZMrsKDFiCmIfEyMf7ZkVZqYGrDApeuBYimn1FyYS1oR/0c0l8JgfNdPKZEpzgh1zAfPKnxrJkXWHpNFKDrCh1IB2gpEI/GyZl4iQPhpnjJu/hkeFxRhDsaV4RqdYF9unx89falybXd4/2rhLswZLgniWo7xNy2MP5bzBtDCphZXmy82nsKxLz5XUvD4dmMLATmPmNS+08lYELor8dMziHaN0wX8B81k00HI3BtvxcgBnzpZl/+12GGLj+UOIr7XrELFKMCYrYW6yrIlegdu4kTljuKVrEESjlMnykYTJQEFTOuF8z0HSbeUOvo+euI53+v1wsM7Qc=
