language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
deploy:
  provider: heroku
  api_key:
    secure: 1jzYC9dfr+DAsl1CsZjrZEY9J1g3XyypQN+khAt8wxfvuU8R7HVj2vxLVz0B80dNkIQxAb+ucna5Z1T6f52SRsZDlkyrkssOOvcAvY2d+LQwzgLbZeFwsQAt7Ex+i/QPIYENlsy0lSP1D6VLy4jBmZQth/MRjsHD2kzbIPtvffS6LLGsxLH58GWfFaupbL6ROWHShxxyAS98zPzdz5dcHB1gnk4HjEo1G/tCFZKT7TkhAbceP5l0J5osKKEJoCqkdXUaU5cj58vJ/oKaTHlBHONSpi/cLh3uCbSmHatCteuhccoNMNyBfURX2g+WlJgz8EyKZqrjUexdxRJJXa6i99/DFtmCcZb1OC0KWi9A8ud/K2bdDSoVtKveCjBrIag62qMamI6sSA+8NKkhjPivbPlejj1Fh+PztRaMr5KxgjZPbT0pMY+x0uKk1vd+kSiObooBjOnOMk3Gdo6hW/Ax0NFZS61gJYj4YaMrx8/pJdBNoNie76NvVQ9BmN9utF6J59eRY/3wE7td8WMeD/882eFLguGGFCER/M2OXEeVLyPKFpswNVAfkxWVph5Pc/QAnLBxgQt189C0sLjO1o3tYlKhu+Se7n7zBav+jiS8FcpZSY7Gnx2a0uvgWyAjIbkZyACOGXVuBRnHF4SvRsTwsjAjp6JrFLoX5BA2oYer3ro=
  app: mysterious-dusk-26630
  on:
    repo: sgraton/AirKong
env:
  global:
    secure: gtK+T3nlwGAyVYqbhHBejXqJAzQ/VqLEm6uphTgRbpMCUtxOZHmHNNrSyc3Giwo3MzcNmyHa1lAVkIO/AtllC4QpXG048tsAfF00Yik+LqwIcXJ7wooca0hF/wAiJ3MPd6Es74pUcUZV0psAKw/rwUTC0q8pBAPCX93xc0B9EygOJouh/UYRMkRfgNhmDFkqFWcRYITLwEMP9Uke0sNoSbkZ/tiT0ni3XRoXzdIE2rH4mcCHpRNLTpSUpmQLny2eNBKj4YeJEWSr7vUmoZiGgNdY0t5i49KLnoQAlBpoLZbPKZzJme6rHZc5ngnfGxXy1uCiLJVZnV2CGOacQfXSwODhz8HpWhKUi9s2GoFm12r0ESxIZBHVPeNl24jw0FKGHmiagBg3qeQLl//OmULGWbbcOwGU7MNnUjwl9wWOhsJz40qyK62ucsehKaEPbFmSBCW9mUjyM1Jxd2SOOxln+ya/2MRz8hxCBBkMUCttWIpYMpeel3Tb5e4yyV3XEoRmPkPlcyIi+XaLW+6Drn0ZWdXfrbZPzYWGtKfSDQ1B64vR2+LPA8L8YdlTBhyeSlh/GGOCSknwasuQqqKgrL9VU6VglScijChLbphUoKCUS5dxV6wqsJx+RMMTstv7qgoYjXpMw7sRfZavcqgClihkHNcBiooWeqaBS9NZtWuYR/0=
