language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
deploy:
  provider: heroku
  api_key:
    secure: 1jzYC9dfr+DAsl1CsZjrZEY9J1g3XyypQN+khAt8wxfvuU8R7HVj2vxLVz0B80dNkIQxAb+ucna5Z1T6f52SRsZDlkyrkssOOvcAvY2d+LQwzgLbZeFwsQAt7Ex+i/QPIYENlsy0lSP1D6VLy4jBmZQth/MRjsHD2kzbIPtvffS6LLGsxLH58GWfFaupbL6ROWHShxxyAS98zPzdz5dcHB1gnk4HjEo1G/tCFZKT7TkhAbceP5l0J5osKKEJoCqkdXUaU5cj58vJ/oKaTHlBHONSpi/cLh3uCbSmHatCteuhccoNMNyBfURX2g+WlJgz8EyKZqrjUexdxRJJXa6i99/DFtmCcZb1OC0KWi9A8ud/K2bdDSoVtKveCjBrIag62qMamI6sSA+8NKkhjPivbPlejj1Fh+PztRaMr5KxgjZPbT0pMY+x0uKk1vd+kSiObooBjOnOMk3Gdo6hW/Ax0NFZS61gJYj4YaMrx8/pJdBNoNie76NvVQ9BmN9utF6J59eRY/3wE7td8WMeD/882eFLguGGFCER/M2OXEeVLyPKFpswNVAfkxWVph5Pc/QAnLBxgQt189C0sLjO1o3tYlKhu+Se7n7zBav+jiS8FcpZSY7Gnx2a0uvgWyAjIbkZyACOGXVuBRnHF4SvRsTwsjAjp6JrFLoX5BA2oYer3ro=
  app: mysterious-dusk-26630
  on:
    repo: sgraton/AirKong
env:
  global:
    secure: VrvF+iSMLzLlSvwL6rAaIVVzK//rvQg+Svju+XIhSVVEmqLuOCnCYl2fydMHUBaFfEvP3Fgeayg4CucQF42UNI/NPc5M/HP95y34MJI9zj/N8Uh9sgevyCFxB7tdMYqbUJtQQprlHB6ou6wYvDdR9Xn+ESWZ8mrF8Z/9WhqY4MhYTxlPQuWVfnR/Fi+tPdSfFuIrDGtp2M70Tzwzvnq4RoINjF5hRstDAnGNTdBZz3LIBe1hsYeCGFL8jEFKaYgC3bw8JI0tQ8GOG1/iFM0F4rXpk8VC/NRDz5J8SBQ2ZC0rcpNnLhwbZ+rd1xPSQ0KJjkmZm1JSXvsk3dS9q5PGU4fAcy63pB1mAPTpjnA/+iE0ebafNCxLrK73dcLgHZaRcAg1dRcGY/NTLJAi1DKbklhHIzzDbRkg7giMPOswxLXachhxeJw19xtsploCDZcwkv0ZpHQNusvsQM2BrZ7lSIAmu2Djnt48qPRdEez7tWxAdNXXUXvGwlY/9UjG6U2IF052qOauHS2ajOu97nvZPZo+xO8JF9NTuZpztTUKxGCASKGrurCZBTECGdRGFwj/QsNX9KdyG9y4NU19TDQw45gf/EDMB9se3/ixwEpDE/vN/suhtxzLE3Ddm14ihqwna6l+s+jHb37EQcF2awyV8ynJAEqVlWsdz+RXb0AT4o0=
